tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: organisation
            field:
              input_type: text
              antlers: false
              type: text
              display: Organisation
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
          -
            handle: name
            field:
              input_type: text
              antlers: false
              type: text
              display: Name
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
          -
            handle: firstname
            field:
              input_type: text
              antlers: false
              type: text
              display: Vorname
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
          -
            handle: email
            field:
              input_type: email
              antlers: false
              type: text
              display: E-Mail
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
                - email
          -
            handle: phone
            field:
              input_type: tel
              antlers: false
              type: text
              display: Telefon
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: area
            field:
              options:
                bildung: Bildung
                gesundheit: Gesundheit
                sensebezirk: Sensebezirk
              taggable: false
              push_tags: false
              multiple: false
              clearable: false
              searchable: true
              cast_booleans: false
              type: select
              display: Bereich
              icon: select
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
              placeholder: 'Bitte wählen...'
          -
            handle: remarks
            field:
              antlers: false
              type: textarea
              display: 'Kurzbeschrieb (max. 200 Wörter)'
              icon: textarea
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
          -
            handle: contribution
            field:
              antlers: false
              type: textarea
              display: 'Beitrag zur Zielerreichung des SDGs'
              icon: textarea
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
