title: Settings
fields:
  -
    handle: show_maps
    field:
      default: true
      type: toggle
      display: 'Show maps'
      icon: toggle
      listable: hidden
      instructions_position: above
      visibility: visible
      replicator_preview: true
      hide_display: false
  -
    handle: debug
    field:
      default: false
      type: toggle
      display: Debug
      icon: toggle
      listable: hidden
      instructions_position: above
      visibility: visible
      replicator_preview: true
      hide_display: false
  -
    handle: template
    field:
      hide_partials: true
      blueprint: false
      type: template
      display: Template
      icon: template
      listable: hidden
      instructions_position: above
      visibility: visible
      replicator_preview: true
      hide_display: false
  -
    handle: layout
    field:
      hide_partials: true
      blueprint: false
      type: template
      display: Layout
      icon: template
      listable: hidden
      instructions_position: above
      visibility: visible
      replicator_preview: true
      hide_display: false
